import Head from "next/head";
import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import Form from "~/components/page/contact/Form";
import Hero from "~/components/page/contact/Hero";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Maps Voyage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
          <Hero />
          <Form />
        </div>
        <Footer />
      </main>
    </>
  );
}
