import type { Destination } from "@prisma/client";
import { PrismaClient } from "@prisma/client";
import type { GetStaticProps } from "next";
import Head from "next/head";
import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import AllDestinations from "~/components/page/destination/AllDestinations";
import Hero from "~/components/page/destination/Hero";

interface DestinationsPageProps {
  destinations: Destination[];
}

export default function Destinations({ destinations }: DestinationsPageProps) {
  return (
    <>
      <Head>
        <title>Maps Voyage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <AllDestinations destinations={destinations} />
        <Footer />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const prisma = new PrismaClient();
  const destinations = await prisma.destination.findMany({});
  await prisma.$disconnect();

  return {
    props: { destinations },
  };
};
