import Head from "next/head";
import Navbar from "~/components/Navbar";
import About from "~/components/page/landing/About";
import Destinations from "~/components/page/landing/Destinations";
import Hero from "~/components/page/landing/Hero";
import Tours from "~/components/page/landing/Tours";

export default function Home() {
  return (
    <>
      <Head>
        <title>Maps Voyage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <About />
        <Destinations />
        <Tours />
      </main>
    </>
  );
}
