import Head from "next/head";
import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import AllTours from "~/components/page/tour/AllTours";
import FilterBox from "~/components/page/tour/FilterBox";
import SearchBox from "~/components/page/tour/SearchBox";
import Banner from "~/components/utility/Banner";

export default function Tours() {
  return (
    <>
      <Head>
        <title>Maps Voyage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Banner title="Tours" />
        <AllTours />
        <SearchBox />
        <FilterBox />
        <Footer />
      </main>
    </>
  );
}
