import Head from "next/head";
import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import AllTours from "~/components/page/tour/AllTours";
import FilterBox from "~/components/page/tour/FilterBox";
import SearchBox from "~/components/page/tour/SearchBox";
import Banner from "~/components/utility/Banner";

export default function Tours() {
  return (
    <>
      <Head>
        <title>Maps Voyage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Banner
          img="https://images.unsplash.com/photo-1500964757637-c85e8a162699?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=903&q=80"
          title="Tours"
        />
        <div className="mx-auto grid max-w-7xl grid-cols-1 md:grid-cols-3">
          <div className="md:col-span-2">
            <AllTours />
          </div>
          <div className="flex flex-col">
            <SearchBox />
            <FilterBox />
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
